export default {
    Fiction: [
      'Romance',
      'Horror',
      'Young Adult',
      'Science Fiction',
      'Short-story',
      'Suspense',
      'Thriller',
      'Coming of age',
      'Action & Adventure',
      'Childrens',
      'Chicklit',
      'Comic book',
      'Alternate history',
      'Anthology',
      'Classic',
      'Graphic Novel',
      'Historical Fiction',
      'Paranormal Romance',
      'Picture Book',
      'Poetry',
      'Political Thriller',
      'Satire',
      'Western', 
    ],

    Non_fiction: [
      'Art/architecture',
      'Autobiography',
      'Biography',
      'Buisness/economics',
      'Crafts/hobbies',
      'Cookbook',
      'Diary',
      'Dictionary',
      'Encyclopedia',
      'Guide',
      'Health/fitness',
      'History',
      'Home & garden',
      'Humor',
      'Jounal',
      'Math',
      'Memoir',
      'Philosopy',
      'Prayer',
      'Religion, & New age',
      'Textbook',
      'Review',
      'Science',
      'Self help',
      'Sports & Liesure',
      'Travel',
      'True crime'

    ]

  }
